resolve ninja warnings
donadigo/wingpanel-indicator-namarupa pull request #14
Opened 2020-10-19 16:46 UTC by Lafydev

Resolve ninja warnings (about deprecated widgets...)

2020-10-20 14:53 UTC, Lafydev commented
![warnings namarupa](https://user-images.githubusercontent.com/44295362/96603844-b7ce4180-12f4-11eb-9faa-b625bb5d4bac.png)

2020-10-21 08:10 UTC, Lafydev commented
solve issue #4

2020-11-03 13:40 UTC, Lafydev commented
screenshot with submenus
![namarupa](https://user-images.githubusercontent.com/44295362/97991984-650b8400-1de2-11eb-9f69-7ba7b79a43e4.png)

2020-11-05 09:14 UTC, Lafydev commented
Please can you tell me what you are waiting from the settings button ?

2020-11-05 12:47 UTC, lainsce commented
The original idea was a Switchboard plug where one could hide or rearrange the icons inside the indicator popover.

2020-11-10 08:20 UTC, Lafydev commented
> The original idea was a Switchboard plug where one could hide or rearrange the icons inside the indicator popover.

Hum, very ambitious but I'll stop here, perhaps we just need a new .deb file for easy install.

2020-11-10 11:57 UTC, lainsce requested changes
Left some parts to fix to fit code style guidelines.

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +    private Gtk.RadioButton? group_radio=null ;
Time for some code styling changes to fit elementary guidelines.

```suggestion
    private Gtk.RadioButton? group_radio = null;
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +                    entry.menu.popup_at_widget (icon.parent,  0, 0);        //entry.menu.popdown ();
```suggestion
                    entry.menu.popup_at_widget (icon.parent, 0, 0);
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +            button.set_state_flags (item.get_state_flags (),true);
```suggestion
            button.set_state_flags (item.get_state_flags (), true);
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +		const int ATK_CHECKBOX =8;
```suggestion
		const int ATK_CHECKBOX = 8;
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +		const int ATK_RADIO =44;
```suggestion
		const int ATK_RADIO = 44;
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +       group_radio = ( item_type == ATK_RADIO)? group_radio:null;
```suggestion
       group_radio = (item_type == ATK_RADIO)? group_radio:null;
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +            button.set_state_flags (state,false);
```suggestion
            button.set_state_flags (state, false);
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +                button.active =((item as Gtk.CheckMenuItem).get_active ());
```suggestion
                button.active = ((item as Gtk.CheckMenuItem).get_active ());
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +		}
```suggestion
		if (item_type == ATK_RADIO) {
		    var button = new Gtk.RadioButton.with_label_from_widget (group_radio,label) {
		       margin = 5,
		       margin_start = 10
		    };
		    if (group_radio == null) {
		        group_radio = button;
		    }
		    
	            button.set_active(active);
			
		    // do not remove
                  button.clicked.connect (() => {
                        item.activate ();
                  });
			
		    button.activate.connect (() => {
			item.activate();
                       (item as Gtk.RadioMenuItem).set_active (button.get_active ());
                   });
			
		    return button;
		}
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +			button.text=label;
```suggestion
			button.text = label;
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +                (button as Gtk.ModelButton).icon= (image.pixbuf);
```suggestion
                (button as Gtk.ModelButton).icon = (image.pixbuf);
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +            button.set_state_flags (state,true);
```suggestion
            button.set_state_flags (state, true);
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +				back_button.menu_name="main_grid";
```suggestion
		    back_button.text = (_("Back"));
		    back_button.inverted = true;
		    back_button.menu_name = "main_grid";
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +				});
```suggestion
		     submenu.remove.connect ((item) => {
			 var w = menu_map.get (item);

        		 if (w != null) {
            		     sub_list.remove (w);
            		     submenu_map.unset (item);
        		 }	
		    });
```

2020-11-10 11:57 UTC, lainsce commented on src/AyatanaIndicator.vala
> +				button.menu_name="submenu";
```suggestion
		      button.text = label;
		      button.menu_name = "submenu";
```

2020-11-10 11:57 UTC, lainsce commented on src/Indicator.vala
> +	public int cpt=0; /* count indicators */
```suggestion
	public int cpt = 0; /* count indicators */
```

2020-11-10 11:57 UTC, lainsce commented on src/Indicator.vala
> +		 if (main_box == null) {init_main_box();}
```suggestion
		    if (main_box == null) {
		        init_main_box ();
		    }
```

2020-11-10 11:57 UTC, lainsce commented on src/Indicator.vala
> +				if (cpt==0) {switch_stack (false);}
```suggestion
				if (cpt == 0) {
				    switch_stack (false);
				}  
```

2020-11-10 11:57 UTC, lainsce commented on src/Indicator.vala
> +		if (main_box == null) {init_main_box();}
```suggestion
		if (main_box == null) {
		    init_main_box ();
		}
```

2020-11-10 11:57 UTC, lainsce commented on src/Indicator.vala
> +		blacklist.add("nm-applet"); //old network indicator (duplicate)
```suggestion
		blacklist.add ("nm-applet"); //old network indicator (duplicate)
```

2020-11-10 11:57 UTC, lainsce commented on src/Indicator.vala
> +		msgdial.destroy(); //dialog without parent =>not perfectly closed
```suggestion
		string msg = cpt.to_string () + " item(s)\n";
		var msgdial = new Gtk.MessageDialog (null,
		                                     Gtk.DialogFlags.MODAL,
                                                   Gtk.MessageType.INFO,
                                                   Gtk.ButtonsType.CLOSE,
                                                   msg);
		msgdial.set_title (_("Information"));
		msgdial.run ();
		msgdial.destroy (); // dialog without parent => not perfectly closed
```

2020-11-12 16:18 UTC, lainsce commented
OK< all seems good. Merging.

2020-11-12 16:18 UTC, merged

2020-11-12 16:33 UTC, Lafydev commented on src/AyatanaIndicator.vala
> +		    var button = new Gtk.RadioButton.with_label_from_widget (group_radio,label) {
I think it's not a } but ;  l.288  ? I don't understand this change

2020-11-12 16:41 UTC, Lafydev commented
Thanks a lot for merging the changes. 
Please can you change line 288 it is a semi-column at the end of the line.